### ISSUE TITLE
Is it possible to add a description?

### ISSUE THREAD

**Issue by xXAvoraXx** [CrystallizeAPI/node-vipps#8]
Hello, I want to add Vipps integration for local businesses to my application, the npm package you wrote caught my attention, but I couldn't see much explanation. Are you able to assist?

Thanks.

**Comment by hakonkrogh** [comment]
Hi. You can check out an example implementation on our Service API boilerplate: https://github.com/CrystallizeAPI/service-api-boilerplate/tree/main/src/services/payment-providers/vipps
